Algoritmo "Variaveis2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Primeiro Programa curso Udemy
// Autor(a)    : Dickin Tadeu
// Data atual  : 29/11/2021
Var
// Seção de Declarações das variáveis 
//Primeiro nome
//segundo nome
//Idade
//Cidade
//Endereco

   primeiroNome, segundo Nome, cidade, endereco: caractere
   idade inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo