Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Primeiro Programa curso Udemy
// Autor(a)    : Dickin Tadeu
// Data atual  : 25/11/2021
Var
// Seção de Declarações das variáveis 
   nota: inteiro, nota2: real, nome: caracter, passou: logico

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo